Structs bye oop
Dr-Nekoma/RacketowerDB pull request #8
Opened 2023-11-11 01:39 UTC by EduardoLR10

2023-11-11 04:03 UTC, EduardoLR10 commented
You can read more about how cursed this is [here](https://duing.dev/posts/ooptypeclasses/)

2023-11-12 06:03 UTC, z-silver requested changes

2023-11-12 06:03 UTC, z-silver commented on util.rkt
> +               [if newline-flag
Is there a reason for the square brackets here?

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +      schema))
Given that this is a writing function, do we really need to return this?

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +        schema
Given that this is a writing function, do we really need to return this?

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +           (close-output-port out)
We should use [`call-with-output-file`](https://docs.racket-lang.org/reference/file-ports.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._call-with-output-file%29%29) here instead.

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +      (close-output-port out))))
We should use [`call-with-output-file`](https://docs.racket-lang.org/reference/file-ports.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._call-with-output-file%29%29) here instead.

2023-11-12 06:03 UTC, z-silver commented on io.rkt
>        (close-output-port out)))
We should use [`call-with-output-file`](https://docs.racket-lang.org/reference/file-ports.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._call-with-output-file%29%29) here instead.

2023-11-12 06:03 UTC, z-silver commented on ast.rkt
> +        (if (eq? received-bytes-size (type-byte-size self))
Unless the size of types is guaranteed not to be larger than a fixnum, we should use `equal?` instead of `eq?`.

2023-11-12 06:03 UTC, z-silver commented on ast.rkt
> +   {define (deserialize _self byte-stream)
Is there a reason for the curly braces here?

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +           (real-lines (port->bytes-lines in))
```suggestion
           (real-lines (port->bytes-lines in #:close? #t))
```

2023-11-12 06:03 UTC, z-silver commented on io.rkt
> +      (define-values (table table-consumed) (deserialize struct:table (port->bytes in)))
```suggestion
      (define-values (table table-consumed) (deserialize struct:table (port->bytes in #:close? #t)))
```

2023-11-12 17:56 UTC, EduardoLR10 commented on io.rkt
> +      schema))
Yes, we do. A writing process of values of a table also updates the field `row-id`  which controls how many bytes we will jump as offset in order to preserve previously written data.

2023-11-12 17:56 UTC, EduardoLR10 commented on io.rkt
> +        schema
Yes, we do. A writing process of values of a table also updates the field row-id which controls how many bytes we will jump as offset in order to preserve previously written data.

2023-11-12 20:09 UTC, z-silver requested changes
Just some minor readability improvements this time.

2023-11-12 20:09 UTC, z-silver commented on io.rkt
> +             #:exists 'can-update)
```suggestion
           (call-with-output-file file-name #:exists 'can-update
             (lambda (out)
               (file-position out off-set)
               (write-bytes converted-row out)))
```

2023-11-12 20:09 UTC, z-silver commented on io.rkt
> +         #:exists 'truncate)))
```suggestion
      (call-with-output-file file-name #:exists 'truncate
        (curry write-bytes serialized-table))))
```

2023-11-12 20:09 UTC, z-silver commented on io.rkt
> +        #:exists 'truncate))))
```suggestion
      (call-with-output-file file-name #:exists 'truncate
        (lambda (out)
          (~>> (group-by (compose give-identifier cdr) schema-list)
               (map (curry write-entity-to-disk out))))))))
```

2023-11-12 20:16 UTC, z-silver approved these changes

2023-11-12 20:17 UTC, merged